// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqvwhebruxlbnjnknonf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_BOeLEyV0SusGNqyBSiZJ3g_vMNLq-Q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase  /client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});