// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqvwhebruxlbnjnknonf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxdndoZWJydXhsYm5qbmtub25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTI4NzYsImV4cCI6MjA2OTg2ODg3Nn0.3BQCeHuNG326VGPhWrGJr3xADOXD_eUnZWe5E06Zq9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});